version: "3"

networks:
  net-pihole:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24
services:
  unbound:
    container_name: unbound
    image: klutchell/unbound
    networks:
      net-pihole:
        ipv4_address: 172.24.0.2
    hostname: unbound
    ports:
      - '5053:5053/udp'
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      net-pihole:
        ipv4_address: 172.24.0.3
    hostname: pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '5380:80/tcp'
      - '53443:443/tcp'
    environment:
      TZ: 'America/Chicago'
      PIHOLE_DNS_: 172.24.0.2#5053
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
