version: "3"

networks:
  unbound-pihole:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
services:
  unbound:
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - 5335:53/udp
      - 5335:53/tcp
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf
      - ./root.hints:/var/unbound/etc/root.hints
    restart: always
    networks:
      unbound-pihole:
        ipv4_address: 10.5.0.100
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "5380:80/tcp"
      - "53443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      PIHOLE_DNS_: 127.0.0.1;10.5.0.100#5335
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - unbound-pihole
